"""
Reporter Node
In:  all state fields
Out: final_report (full markdown brief) + citation_links (conceptual relationship graph)
Real impl: Groq llama-3.3-70b-versatile synthesizes everything into a structured report,
then infers conceptual relationships between patents for the frontend graph.
"""
import json
import logging
from typing import Any, Dict, List

from groq import AsyncGroq
from tenacity import retry, stop_after_attempt, wait_exponential

from supabase import AsyncClient

from app.agents.state import LandscapeState
from app.core.config import settings

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = (
    "You are a patent landscape analyst. Write a comprehensive patent landscape brief in markdown."
    " Structure: # Patent Landscape Brief, then ## Executive Summary, ## Prior Art Analysis (one section per cluster),"
    " ## White Space Opportunities (with patent ID citations), ## Recommended Next Steps."
    " Be specific and cite patent IDs where relevant."
)


def _build_mock_report(state: LandscapeState) -> str:
    idea = state.get("invention_idea", "Unknown Invention")
    n_patents = len(state.get("deduped_patents", []))
    clusters = state.get("clusters", [])
    whitespace = state.get("white_space_analysis", "")

    cluster_section = ""
    for i, c in enumerate(clusters, 1):
        patent_list = ", ".join(f"[{p}]" for p in c.get("patent_ids", []))
        cluster_section += f"\n### Cluster {i}: {c['theme_name']}\n{c['description']}\n\n**Key Patents:** {patent_list}\n"

    return f"""# Patent Landscape Brief

## Invention
> {idea}

---

## Executive Summary
This landscape analysis examined **{n_patents} patents** across **{len(clusters)} thematic clusters**. The prior art reveals a mature field in semantic retrieval and patent classification, with identifiable whitespace in real-time collaborative tooling and explainable AI for examiner workflows.

---

## Prior Art Clusters
{cluster_section}

---

## White Space Opportunities
{whitespace}

---

## Recommended Next Steps
1. File provisional covering real-time collaborative patent drafting architecture
2. Conduct freedom-to-operate (FTO) analysis against Cluster 1 before development
3. Monitor continuation applications from TechCorp Inc. and AI Research Labs

---

*Generated by Patent Landscape Mapper (mock mode)*
"""


async def reporter_node(state: LandscapeState, supabase: AsyncClient) -> Dict[str, Any]:
    """Synthesize all state into a final markdown report."""
    search_id = state["search_id"]
    logger.info("[reporter] starting for search_id=%s", search_id)

    await supabase.table("searches").update({"current_step": "writing_report"}).eq(
        "id", search_id
    ).execute()

    if settings.mock_mode:
        report = _build_mock_report(state)
        logger.info("[reporter] mock mode — report generated (%d chars)", len(report))
        return {"final_report": report, "citation_links": []}

    cluster_text = "\n\n".join(
        f"### {c['theme_name']}\n{c['description']}\nPatents: {', '.join(c.get('patent_ids', []))}"
        for c in state["clusters"]
    )
    user_content = (
        f"Invention: {state['invention_idea']}\n\n"
        f"Prior Art Clusters:\n{cluster_text}\n\n"
        f"White Space Analysis:\n{state['white_space_analysis']}"
    )

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=1, max=10))
    async def _call_groq() -> str:
        client = AsyncGroq(api_key=settings.groq_api_key)
        response = await client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
        )
        return response.choices[0].message.content

    report = await _call_groq()
    logger.info("[reporter] real mode — report generated (%d chars)", len(report))

    # ── Citation link inference ──────────────────────────────────────────────
    top_patents: List[Dict[str, Any]] = state.get("deduped_patents", [])[:30]
    patent_list_text = "\n".join(
        f"{p.get('patent_id', '')}: {p.get('title', '')}"
        for p in top_patents
        if p.get("patent_id")
    )

    @retry(stop=stop_after_attempt(2), wait=wait_exponential(multiplier=1, min=1, max=5))
    async def _generate_citation_links() -> str:
        client = AsyncGroq(api_key=settings.groq_api_key)
        response = await client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": (
                        "Given these patents from a landscape analysis, identify which patents are "
                        "conceptually related (similar technology, shared problem domain, or one builds "
                        "on the other).\n"
                        "Return ONLY a JSON array of objects with: source (patent_id), target (patent_id), "
                        "strength (0.5-1.0). Include only meaningful relationships, max 40 links.\n"
                        f"Patents:\n{patent_list_text}"
                    ),
                }
            ],
        )
        return response.choices[0].message.content

    citation_links: List[Dict[str, Any]] = []
    try:
        raw = await _generate_citation_links()
        # Strip markdown fences if present
        raw = raw.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        parsed = json.loads(raw.strip())
        if isinstance(parsed, list):
            citation_links = parsed
        logger.info("[reporter] generated %d citation links", len(citation_links))
    except Exception as e:
        logger.warning("[reporter] citation link generation failed, using []: %s", e)

    return {"final_report": report, "citation_links": citation_links}
